# Generated by Django 5.1.7 on 2025-03-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_customuser_age_alter_customuser_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
