# Generated by Django 5.1.7 on 2025-03-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_customuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_subscribed',
            field=models.BooleanField(default=False, help_text='Indicates if the user has an active subscription'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
