# Generated by Django 5.1.7 on 2025-03-19 18:17
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('MyApp', '0005_customuser_is_otp_verified_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_date',
            field=models.DateTimeField(
                blank=True,
                null=True,
                default=None,  # Explicitly set to None for existing rows
                help_text='Date of subscription activation'
            ),
            preserve_default=False,  # Avoid prompting for a default value
        ),
    ]